FROM alpine:edge

ENV REFRESHED_AT=2017-11-23

RUN apk add --update \
  bash \
  erlang=20.2.2-r2 \
  elixir=1.6.0-r0 \
  erlang-crypto \
  erlang-xmerl \
  erlang-parsetools \
  erlang-syntax-tools \
  erlang-runtime-tools \
  git \
  make

